### ISSUE TITLE
How to view more details in Points transfers list 

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#79] opened 2018-03-09 07:40 UTC
As a customer, when I go to **Points transfers list**, I don't find any fields to know "why I had/lost these points". For example, If I was added 100 points by **follow_fan_page** event, I should know the 100 points from that event. In fact, all I can see from that Points transfer is just "adding" type, "100 points" and many other fields but no reason, even for the admin (using Admin page). The api just returns like:

```
"transfers": [
        {
            "pointsTransferId": "b18df807-046d-4537-b341-cdf02a0cffdc",
            "accountId": "64780e89-384a-4b08-9c3e-0ff3aefb3cda",
            "customerId": "b292d0e7-41a9-48e1-81ea-5ee76258aa7f",
           
 "customerFirstName": "catbui",
            "customerLastName": "p",
            "customerEmail": "chaup@p.com",
            "customerPhone": "121212",
            "createdAt": "2018-03-12T08:08:25+0100",
            "value": 1000,
            "state": "active",
            "type": "adding",
            "issuer": "system",
            "expireAt": "2018-03-13T08:08:25+0100"
        } 
        ...
```

Can I get the missing field (reason to add points) in openloyalty ? 
Please help.
Thanks.

**Comment by karolbzik** [comment] 2018-03-12 17:33
@catbuilts thank you for the comment. Today we discussed it with the product team and agreed to make some improvements. We will add missing information the area of comment field in the Admin Cockpit as it. It will be released with 2.4.0. in 2 weeks together with other improvements, we have on the roadmap. I will let you know when it will be available.

**Comment by colejarczyk** [comment] 2018-03-22 13:21
@catbuilts Could you write which API address you have tried? I'll add missing comment field.

**Comment by catbuilts** [comment] 2018-03-22 15:29
Hi @colejarczyk,
I use **/api/points/transfer?customerId={customer-id}&page=1&perPage=20**.

It returns something like this:
```
{
    "transfers": [
        {
            "pointsTransferId": "e82c96cf-32a3-43bd-9034-4df343e5f433",
            "accountId": "840a48df-a3a7-43e6-93c6-13abb4699855",
            "customerId": "00000000-0000-474c-b092-b0dd880c07e2",
            "customerFirstName": "Jane",
            "customerLastName": "Doe",
            "customerLoyaltyCardNumber": "0000",
            "customerEmail": "user-temp@oloy.com",
            "customerPhone": "111112222",
            "createdAt": "2018-02-20T17:29:43+0100",
            "value": 100,
            "state": "active",
            "type": "adding",
            "issuer": "system",
            "expireAt": "2018-03-22T17:29:43+0100"
        },
        ...
    ] 
}
```

By the way, can you please explain the meaning of three fields **state**, **type**, and **issuer** above.
I want to know **state** field here can be _active_ and what ?
The same question for **type** and **issuer**.
And what are the meaning of these fields.

Thank you in advance.

**Comment by bizr** [comment] 2018-03-22 17:29
State: A point transfer can be cancelled by an admin, deactivated
Type: Adding or spending, here you can find all transactions, adding points, or removing
Issuer: The user that issued the transaction, if added from demo data, 'system' will add it, add a transaction from the admin cockpit with your username and you will see a different issuer. So it's who added those points, just imagine they could be added from the cockpit but also added from an e-shop script after a customer purchase..

**Comment by colejarczyk** [comment] 2018-03-23 11:17
@catbuilts 

Point transfer has a field "comment" you can use. You can check it in the administration panel and manually add a point transfer with a comment. This comment will be available in the API response as follow

```
    {
      "pointsTransferId": "e82c96cf-32a3-43bd-9034-4df343e5f333",
      "accountId": "def6af83-453d-431d-8103-c599d84ad811",
      "customerId": "00000000-0000-474c-b092-b0dd880c07e2",
      "customerFirstName": "Jane",
      "customerLastName": "Doe",
      "customerLoyaltyCardNumber": "0000",
      "customerEmail": "user-temp@oloy.com",
      "customerPhone": "111112222",
      "createdAt": "2018-03-23T11:46:20+0100",
      "value": 100,
      "state": "active",
      "type": "spending",
      "comment": "Example comment",
      "issuer": "system",
      "expireAt": "2018-04-22T11:46:20+0200"
    },
```
If comment is empty then it won't be added to the response.

* ```issuer``` is a field you can use to indicate who added points manually. The default value is a ```system```. Other possible values are ```admin``` and ```seller```. So it indicates who added points.
* ```type``` - you need to be aware, that OL doesn't save a customer balance anywhere. It's calculated based on transfer list. So OL adds or substract points and then have a customer balance. 
* ```state``` - points can expire, so when points are expired are inactive. Only points that where have type ```adding``` can expire or can be canceled.

About questions
1. Point transfer that has been canceled has a ```state = canceled```
2. Yes.
3. No, it's still system because the system is responsible for generating a points transfer. However if you log in into the administration panel and try to add points transfer manually, the issuer will be the admin.

**Comment by catbuilts** [comment] 2018-04-06 02:29
Hi @colejarczyk ,

Have you added the missing field (how to get/lose points) to Points Transfer ? I haven't found it yet on the new version (ver 2.3.0). 

Thank you.

**Comment by catbuilts** [comment] 2018-04-06 11:35
Hi @colejarczyk 
Thanks for your help, but I dont think it will create a comment by default.

I created a post request like this: 

> http://openloyalty.localhost/api/v1/earnRule/facebook_like/customer/00000000-0000-474c-b092-b0dd880c07e1

(add 100 points for John).
In the admin page, I cant find the comment with "**facebook_like**" like I expect. Just an empty line.

John | Doe | 11111 | user@oloy.com | active | adding | 100 | (empty here)  | 2018-04-06 18:38 | Not set | Not set | system
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Can you take a look on this.
Thank again.

**Comment by catbuilts** [comment] 2018-05-09 03:35
Hi, 

Any updates for this?
It seems to me that the missing field  is not updated yet in Version 2.4.1

**Comment by colejarczyk** [comment] 2018-05-21 14:21
@catbuilts 
I've created an internal ticket to verify it. It's possible that it's related only to custom earning points rules. I will get back to you with an updated soon.

**Comment by colejarczyk** [comment] 2018-05-24 05:10
@catbuilts 

Our testers confirmed that it's not working for custom earning points rules. I've created a ticket internally and we will resolve it in next version 2.6.0 as version 2.5.0 is already in the testing phase.

**Comment by colejarczyk** [comment] 2018-06-05 18:29
Hi @catbuilts 

Please check our latest version 2.6.0. This issue has been fixed.

**Closed** 2018-06-18 10:00 UTC
Labels: improvement
